[package]
name = "cipher_stratego"
version = "0.1.0"
description = "Created with Arcium & Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "cipher_stratego"

[features]
default = ["no-idl", "no-log-ix-name"]
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
custom-heap = []
custom-panic = []
anchor-debug = []
## Arcium macros are part of the default build of the program

[dependencies]
anchor-lang = "0.31.1"

# Arcium v2 dependencies
arcium-macros = { version = "0.2" }
arcium-anchor = { version = "0.2", default-features = false }

[dev-dependencies]
arcium-client = { version = "0.2" }
