[package]
name = "check-shot-circuit"
version = "0.1.0"
description = "Arcis circuit for Cipher Stratego's check_shot instruction."
edition = "2021"

[dependencies]
arcis-imports = { version = "0.1.47" }